services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:24
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_READ_ONLY_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
      - SESSION_SECRET=coop-demo-secret
      - WAREHOUSE_ADAPTER=clickhouse
      - ANALYTICS_ADAPTER=clickhouse
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123
      - CLICKHOUSE_USERNAME=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DATABASE=analytics
      - CLICKHOUSE_PROTOCOL=http
      - REDIS_USE_CLUSTER=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCYLLA_HOSTS=scylla:9042
      - SCYLLA_USERNAME=cassandra
      - SCYLLA_PASSWORD=cassandra
      - SCYLLA_LOCAL_DATACENTER=datacenter1
      - OTEL_SERVICE_NAME=COOP_DEMO
      - EXPOSE_SENSITIVE_IMPLEMENTATION_DETAILS_IN_ERRORS=true
      - ALLOW_USER_INPUT_LOCALHOST_URIS=true
      - GRAPHQL_OPAQUE_SCALAR_SECRET=coop-demo-opaque-scalar
      - UI_URL=http://localhost:3000

  postgres:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 2s
      start_period: 2s

  redis:
    image: redis:8.6.1-trixie

  clickhouse:
    image: clickhouse/clickhouse-server:24.3

  scylla:
    image: scylladb/scylla:5.2
    healthcheck:
      test: ['CMD', 'cqlsh', '-e', 'DESCRIBE KEYSPACES']
      interval: 5s
      start_period: 15s
      retries: 10
